import type { StructureEntity } from './StructureEntity.ts'
import { StructureType } from './StructureEntity.ts'

export class RelayNetwork {
  private beacons: StructureEntity[] = []

  register(structure: StructureEntity): void {
    if (structure.type === StructureType.RELAY_BEACON) {
      this.beacons.push(structure)
    }
  }

  unregister(id: number): void {
    this.beacons = this.beacons.filter(b => b.id !== id)
  }

  // Returns true if position is within any active beacon's coverage
  isCovered(x: number, y: number): boolean {
    for (const beacon of this.beacons) {
      if (!beacon.isActive) continue
      const radius = beacon.profile.coverageRadius * (1 + (beacon.tier - 1) * 0.5)
      const dx = x - beacon.x
      const dy = y - beacon.y
      if (dx * dx + dy * dy <= radius * radius) return true
    }
    return false
  }

  // Coordination bonus [1.0 = no bonus, 1.2 = 20% bonus in relay coverage]
  coordinationBonus(x: number, y: number): number {
    return this.isCovered(x, y) ? 1.2 : 1.0
  }

  // Returns all active beacon positions + radii for rendering
  getCoverageZones(): Array<{ x: number; y: number; radius: number }> {
    return this.beacons
      .filter(b => b.isActive)
      .map(b => ({
        x: b.x, y: b.y,
        radius: b.profile.coverageRadius * (1 + (b.tier - 1) * 0.5),
      }))
  }

  // Total CP/s generated by active beacons and science labs
  getTotalCPGeneration(allStructures: StructureEntity[]): number {
    return allStructures
      .filter(s => s.isActive)
      .reduce((sum, s) => sum + s.profile.cpGeneration, 0)
  }
}
